### ISSUE TITLE
Script identified a path and abort with reason Unable to identify path

### ISSUE THREAD

**Issue by timofeika** [solacelost/update-arcdps#1]
Screenshot of the issue: https://i.imgur.com/NgHhOTt.png

**Comment by solacelost** [comment]
~Any way you could get me a copy and paste of the red error text since your (amazing) background picture and the image compression make it unreadable?~

Nevermind, the quality is only potato on mobile. Looks fine here and I think I've figured out the problem. Working on a fix now.

**Comment by solacelost** [comment]
Nevermind, the quality is only potato on mobile. Looks fine here and I think I've figured out the problem. Working on a fix now.

**Comment by solacelost** [comment]
Would you mind giving commit 468fab39e041268b9bd4cd36850052e18332dcb1 a shot over on [the bugfix branch](/solacelost/update-arcdps/tree/bugfix/find-gw2)? I don't have a great way to test this very thoroughly right now, but it seems to do everything I expect it would to fix this issue.

**Comment by timofeika** [comment]
Sure, i test it, now it cannot identify path, here screenshot again: https://i.imgur.com/PCqCHj7.png

**Comment by timofeika** [comment]
If it helps, i have 4 drive, 2 physical, 3rd is ramdrive and 4th is USB cardreader.

**Comment by timofeika** [comment]
If i set an option "-SearchPath D:\Games", it works like a charm, screenshot again: https://i.imgur.com/QMFLZB3.png
p.s Looks like something wrong, i chose 2 what supposed to build templates only, but he downloaded extras too.

**Comment by solacelost** [comment]
It will download them all, but only enable what you ask. I can change that behavior. I will build some mockups of your situation in a VM and see what I can get it to do. Glad it works for now with the extra option switch!

**Comment by timofeika** [comment]
one more thing, it place arcdps.ini into "guildwars dir/bin64" instead of "guildwars dir/addons/arcdps".

**Comment by solacelost** [comment]
I don't actually own/maintain ArcDPS, so where he drops his configuration file I have no control over. He may have changed it and not updated his documentation. The only thing Update-ArcDPS.ps1 saves is `update_arcdps.xml` in your `%APPDATA%` directory.

My script just downloads updated copies of everything they publish, and then enables the addons you have requested, at every run.

**Comment by solacelost** [comment]
Marking this as closed with no further feedback, and considering recent changes.
